project: 
  type: website

website: 
  page-navigation: true
  title: "Open Sciences for NOAA Fisheries PAM" 
  site-url: "https://sael-swfsc.github.io/OpenScience/" 
  repo-url: "https://github.com/SAEL-SWFSC/OpenScience"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://sael-swfsc.github.io/OpenScience/
        text: "PAM Open Science"
      - icon: github
        href: https://github.com/SAEL-SWFSC/OpenScience
        text: "SAEL Open Science"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: "Pre Meeting Prep"
        contents:
        - content/PAM-SI-Mtg-Prep.qmd
      - section: "Workshop Exercises"
        contents:
        - content/PAM-SI-Mtg-Exercises.qmd
        - content/exercises/PAM-SI-Exercises-IntroText.qmd
        - content/exercises/PAM-SI-Exercises-Authors.qmd
        - content/exercises/PAM-SI-Exercises-Acknowledgements.qmd
        - content/exercises/PAM-SI-Exercises-ListAttendees.qmd
      - href: content/Zotero.qmd
        text: Working with Zotero
      - href: content/Stack-Exchange.qmd
        text: Bioacoustics Stack Exchange

      # - href:
      #   text:


format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
